server:
  port: 8702

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8700/eureka,http://localhost:8699/eureka,http://localhost:8698/eureka
#    register-with-eureka: false
#    fetch-registry: false
#  instance:
#    hostname: localhost

spring:
  application:
    name: springcloud-consumer
