server:
  port: 8702

eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8700/eureka
#    register-with-eureka: false
#    fetch-registry: false
  instance:
    hostname: localhost

spring:
  application:
    name: springcloud-consumer
