package com.tencent.demo.controller;

import java.io.IOException;
import javax.servlet.http.HttpServletResponse;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

/**
 * MockController
 *
 * @author torrisli
 * @date 2024/4/18
 * @Description: MockController
 */
@RestController
public class MockController {

    @GetMapping("/sgid-sso/login")
    public void redirect(@RequestParam String service, HttpServletResponse response) throws IOException {

        response.sendRedirect(service + "?province=1&encryptKey=2&loginType=3&execution=qwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjkqwiksdfghjksdfghjk&_eventId=5&errmsg=");
        return;
    }
}
