server:
  port: 8700

eureka:
  client:
    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
      defaultZone: http://localhost:8700/eureka,http://localhost:8699/eureka
    register-with-eureka: false
    fetch-registry: false
#  instance:
#    hostname: localhost

spring:
  application:
    name: springcloud-eureka-server
